### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by thephilluk** [discord-tickets/bot#215]
**Describe the bug**
unable to Install Bot due to NPM

**To reproduce**
- Clone the Git
- cd into the directory
- run `npm i --production`
- Get the error message shown in the Log below
- try to edit the .env file: get `file or folder doesn't exist` error

**Expected behaviour**
NPM Installing all the modules

**Screenshots**
Gist Link with Log due to length: https://gist.github.com/thephilluk/cc4b65a9d3a91bd3a20915de24ed802f

**Comment by eartharoid** [comment]
If you're going to use a MySQL database then you may be able to continue regardless of the sqlite3 installation error. If you do need to install sqlite3, installation errors are usually caused by missing dependencies.

[This](https://stackoverflow.com/questions/60620327/the-n-api-version-of-this-node-instance-is-1-this-module-supports-n-api-version) suggests updating Node and NPM.

**Comment by thephilluk** [comment]
> If you're going to use a MySQL database then you may be able to continue regardless of the sqlite3 installation error

it doesn't seem to create the .env file... the user/example.config.js is created.



> [This](https://stackoverflow.com/questions/60620327/the-n-api-version-of-this-node-instance-is-1-this-module-supports-n-api-version) suggests updating Node and NPM.

Will try and report back

**Comment by eartharoid** [comment]
Are you sure? If you run the bot and it doesn't find `./.env` it will copy `./example.env` to `./.env` and generate the encryption key. It might just be hidden because it is a dot file. Try `nano .env`.

**Comment by thephilluk** [comment]
NVM... i didn't start the bot yet... i just ran the `npm i --production`... forget my last comment
