### ISSUE TITLE
[BUG] "Robot" Emoji Issues

### ISSUE THREAD

**Issue by GeckoBoy84** [discord-tickets/bot#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The bot has issues with having "robot" as an emoji for a category. It works fine as unicode but not as "robot" or ":robot:

### Expected Behavior

Should work fine as with the other emojis I have tried

### Environment

```markdown
- OS: Pterodactyl - Ubuntu Server 20.04
- Node: 18
- NPM: Unsure
- Bot: 4.0.6
```

### Anything else?

![](https://cdn.discordapp.com/attachments/1127690221505499157/1128978292607815751/image.png)

**Comment by eartharoid** [comment]
I'm not sure why `:robot:` doesn't work, because it does appear to be supported by [`emojilib`](https://github.com/muan/emojilib), but as far as I can tell, this must be a `node-emoji` or `emojilib` issue and I'm not going to investigate further.

As now mentioned at https://discordtickets.app/configuration/categories/#emoji, using the Unicode character is recommended, but names will be attempted for convenience.
